#Group Announcements

## Get all announcements [GET /announces]

+ Response 200 (application/json)
	+ Attributes (array[Announce])

## Get Specific user by message [GET /announces/:announce]

+ Response 200 (application/json)
	+ Attributes (array[Announce])

## Post Create new messages [POST /announces]

+ Response 200 (application/json)
	+ Attributes (array[Announce])

## Put Update users information [PUT /announces/:id]

+ Response 200 (application/json)
	+ Attributes (array[Announce])


