#Group Announcements

## Get all announcements [GET /announce]

+ Response 200 (application/json)
	+ Attributes (array[Announce])

## Get Specific user by message [GET /announce/:announce]

+ Response 200 (application/json)
	+ Attributes (array[Announce])

## Post Create new messages [POST /announce]

+ Response 200 (application/json)
	+ Attributes (array[Announce])

## Put Update users information [PUT /announce/:id]

+ Response 200 (application/json)
	+ Attributes (array[Announce])


