#Group Emails

## Get Email By ID [GET /emails/:id]

+ Response 200 (application/json)
	+ Attributes (array[Email])

## Create new email [POST /emails]

+ Response 200 (application/json)
	+ Attributes ()


