#Group Messages

## Get Message [GET /messages]

+ Response 200 (application/json)
	+ Attributes (array[Message])

## Get Specific user by message [GET /users/:message]

+ Response 200 (application/json)
	+ Attributes (array[Message])

## Post Create new messages [POST /message]

+ Response 200 (application/json)
	+ Attributes (array[Message])

## Put Update users information [PUT /message/:id]

+ Response 200 (application/json)
	+ Attributes (array[Message])

## Get Private Chat Message between two users [GET /users/:uid1/:uid2]

+ Response 200 (application/json)
	+ Attributes (array[Message])

