#Group Notes

## Get all notes [GET /notes]

+ Response 200 (application/json)
	+ Attributes (array[Note])

## Get all the display note [GET /notes/user/:id]

+ Response 200 (application/json)
	+ Attributes (array[Note])

## Post Create new note [POST /notes]

+ Response 200 (application/json)
	+ Attributes (array[Note])

## Put Update users information [PUT /notes/:id]

+ Response 200 (application/json)
	+ Attributes (array[Note])

## Delete Update users information [DELETE /notes/:id]

+ Response 200

