#Group Sessions

## Register and Login [POST /sessions]

+ Request (application/json)
	+ Attributes
		+ username: username (string) - user's id
		+ password: password (string) - user's password

+ Response 200 (application/json)
	+ Attributes (Session)

## Validate a Session [GET /sessions/{session_id}]

+ Parameters
  + session_id: 88888888 (string) - session's id

+ Response 200 (application/json)
	+ Attributes (Session)

## Log Out from a Session [DELETE /sessions/{session_id}]

+ Parameters
    + session_id: 88888888 (string) - session's id

+ Response 200 (application/json)
