#Group Login

## Login [POST /login]

+ Request (application/json)
	+ Attributes
		+ username: username (string) - user's id
		+ password: password (string) - user's password

+ Response 200 (application/json)
	+ Attributes (Session)

