#Group Users

## Get User Directory [GET /users]

+ Response 200 (application/json)
	+ Attributes (array[User])

## Get Specific user by id [GET /users/:id]

+ Response 200 (application/json)
	+ Attributes (array[User])

## Post Create new users [POST /users]

+ Response 200 (application/json)
	+ Attributes (array[User])

## Put Update users information [PUT /users/:id]

+ Response 200 (application/json)
	+ Attributes (array[User])


## Delete a user by id [DELETE /users/:id]

+ Response 200 (application/json)

